name: macos

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        include:
          - build_type: debug
            lto: "n"
          - build_type: releasedbg
            lto: "n"
          # - build_type: releasedbg
          #   lto: "y"

    concurrency:
      group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-macos-${{ matrix.build_type }}-${{ matrix.lto }}
      cancel-in-progress: true

    steps:
      - name: Setup llvm
        run: |
          brew install llvm@20 lld@20

      - name: Setup python
        run: |
          # avoid compile python
          brew install python@3.13
          brew install python-setuptools

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        run: |
          brew install xmake

      - name: Package
        run: |
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export PATH="/opt/homebrew/opt/llvm@20/bin:/opt/homebrew/opt/lld@20/bin:$PATH"
          xmake config --yes --verbose --toolchain=clang --mode=${{ matrix.build_type }} --policies=build.optimization.lto:${{ matrix.lto }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.build_type }}-lto_${{ matrix.lto }}.tar.xz
          path: build/package/*
          compression-level: 0
          if-no-files-found: error
